// Comprehensive character types list
export const CHARACTER_TYPES = [
  // Emotional States
  'angry',
  'sad',
  'happy',
  'intense',
  'calm',
  'romantic',
  'fearful',
  'anxious',
  'confident',
  'vulnerable',
  'playful',
  'serious',
  'sarcastic',
  'cold detached',
  'warm affectionate',
  'mysterious',
  'conflicted',
  'jealous',
  'hopeful',
  'frustrated',
  'nostalgic',
  
  // Personality Traits
  'hero',
  'villain',
  'anti-hero',
  'comic relief',
  'mentor',
  'sidekick',
  'rebel',
  'leader',
  'follower',
  'innocent',
  'wise',
  'naive',
  'cunning',
  'loyal',
  'betrayer',
  'protector',
  'survivor',
  
  // Social Roles
  'parent',
  'child',
  'sibling',
  'friend',
  'lover',
  'enemy',
  'stranger',
  'authority figure',
  'outcast',
  'popular',
  
  // Professional/Occupational
  'student',
  'teacher',
  'doctor',
  'lawyer',
  'cop',
  'criminal',
  'artist',
  'athlete',
  'businessman',
  'soldier',
  
  // Age-related
  'young',
  'old',
  'middle-aged',
  'teenager',
  'elderly'
];

// Synonym mapping for smart search
export const CHARACTER_TYPE_SYNONYMS: Record<string, string> = {
  'mad': 'angry',
  'furious': 'angry',
  'enraged': 'angry',
  'upset': 'sad',
  'depressed': 'sad',
  'joyful': 'happy',
  'cheerful': 'happy',
  'scared': 'fearful',
  'afraid': 'fearful',
  'worried': 'anxious',
  'nervous': 'anxious',
  'sure': 'confident',
  'weak': 'vulnerable',
  'fun': 'playful',
  'grave': 'serious',
  'ironic': 'sarcastic',
  'loving': 'romantic',
  'cold': 'cold detached',
  'warm': 'warm affectionate',
  'enigmatic': 'mysterious',
  'torn': 'conflicted',
  'envious': 'jealous',
  'optimistic': 'hopeful',
  'annoyed': 'frustrated',
  'wistful': 'nostalgic',
  'good guy': 'hero',
  'bad guy': 'villain',
  'antagonist': 'villain',
  'protagonist': 'hero',
  'funny': 'comic relief',
  'guide': 'mentor',
  'assistant': 'sidekick',
  'revolutionary': 'rebel',
  'boss': 'leader',
  'chief': 'leader',
  'subordinate': 'follower',
  'pure': 'innocent',
  'smart': 'wise',
  'foolish': 'naive',
  'clever': 'cunning',
  'faithful': 'loyal',
  'traitor': 'betrayer',
  'guardian': 'protector',
  'fighter': 'survivor',
  'mom': 'parent',
  'dad': 'parent',
  'father': 'parent',
  'mother': 'parent',
  'kid': 'child',
  'brother': 'sibling',
  'sister': 'sibling',
  'buddy': 'friend',
  'partner': 'lover',
  'foe': 'enemy',
  'rival': 'enemy',
  'unknown': 'stranger',
  'authority': 'authority figure',
  'loner': 'outcast',
  'misfit': 'outcast',
  'famous': 'popular',
  'pupil': 'student',
  'professor': 'teacher',
  'physician': 'doctor',
  'attorney': 'lawyer',
  'police': 'cop',
  'thief': 'criminal',
  'painter': 'artist',
  'sportsman': 'athlete',
  'entrepreneur': 'businessman',
  'military': 'soldier',
  'youth': 'young',
  'senior': 'old',
  'adult': 'middle-aged',
  'teen': 'teenager',
  'aged': 'elderly'
};

// Gender options (matching Edit Profile)
export const GENDER_OPTIONS = [
  { value: 'any', label: 'Any' },
  { value: 'male', label: 'Male' },
  { value: 'female', label: 'Female' },
  { value: 'non-binary', label: 'Non-Binary' },
  { value: 'transgender', label: 'Transgender' },
  { value: 'genderqueer', label: 'Genderqueer' },
  { value: 'genderfluid', label: 'Genderfluid' },
  { value: 'agender', label: 'Agender' },
  { value: 'two-spirit', label: 'Two-Spirit' },
  { value: 'other', label: 'Other' }
];

// Skills list (from Edit Profile)
export const AVAILABLE_SKILLS = [
  'Acting', 'Dance', 'Singing', 'Voice Acting', 'Dubbing',
  'Stage Performance', 'Classical Dance', 'Contemporary Dance',
  'Hip Hop', 'Ballet', 'Bharatanatyam', 'Kathak', 'Kuchipudi',
  'Odissi', 'Mohiniyattam', 'Kathakali', 'Martial Arts', 'Stunts',
  'Horse Riding', 'Swimming', 'Gymnastics', 'Acrobatics',
  'Comedy', 'Stand-up Comedy', 'Improv', 'Mimicry',
  'Musical Instrument', 'Guitar', 'Piano', 'Drums', 'Tabla',
  'Flute', 'Harmonium', 'Method Acting', 'Classical Acting',
  'Physical Theatre', 'Puppetry', 'Mime', 'Sketch Comedy',
  'Voice Modulation', 'Dialect/Accent', 'Action Choreography',
  'Fight Choreography'
];

// Languages list (from Edit Profile)
export const AVAILABLE_LANGUAGES = [
  // Indian languages
  'Hindi', 'English', 'Bengali', 'Telugu', 'Marathi', 'Tamil',
  'Gujarati', 'Urdu', 'Kannada', 'Odia', 'Malayalam', 'Punjabi',
  'Assamese', 'Maithili', 'Konkani', 'Manipuri', 'Sindhi',
  'Kashmiri', 'Dogri',
  // Other widely-used languages
  'Spanish', 'French', 'German', 'Italian', 'Portuguese',
  'Russian', 'Chinese (Mandarin)', 'Japanese', 'Korean', 'Arabic'
];
